packages:
  - "frontend"
  - "backend"
catalog:
  "@biomejs/biome": 2.5.1
  typescript: ^5.7.3
allowBuilds:
  "@scarf/scarf": true
  "@swc/core": true
  esbuild: true
  sharp: true
  unrs-resolver: true
